package debugger

import (
	"fmt"
	"strconv"
	"strings"
)

func GenerateProbeGooo(caseReport CaseReport) string {
	probe := caseReport.ProbeIR
	return fmt.Sprintf("gooo typed_resolution_probe v1\nauthority metacode\norigin source=%s fixture=caller_owned case=%s\nprobe id=%s operation=%s capability=%s effect=%s\ninput type=CallerOwnedFixture digest=%s\nresolution from=%s to=%s\nobservation kind=%s expected_ids=%s observed_ids=%s\nclaim id=%s prior=OPEN transition=%s\n", "semantic-ir.json", probe.CaseID, probe.CaseID, probe.Operation, probe.Capability, probe.Effect, probe.FixtureDigest, probe.FromResolution, probe.ToResolution, probe.Observation, strings.Join(probe.ExpectedIDs, ","), strings.Join(probe.ObservedIDs, ","), probe.ClaimID, transitionTarget(caseReport))
}

func GenerateProbeGo(caseReport CaseReport) string {
	probe := caseReport.ProbeIR
	evidence := caseReport.ProbeEvidence
	return fmt.Sprintf(`// Code generated by gooo-resolution-descent-debugger; DO NOT EDIT.
package generatedprobe

// CallerOwnedFixture is the only input accepted by this typed probe.
type CallerOwnedFixture struct {
	CaseID        string
	ClaimID       string
	FixtureDigest string
}

type ProbeEvidence struct {
	ProbeID          string
	Observation      string
	Accepted         bool
	Contradiction    bool
	Capability       string
	Effect           string
	Reason           string
	EvidenceDigest   string
	InputDigest      string
	RunnerDigest     string
	ToolchainDigest  string
}

func Execute(input CallerOwnedFixture) ProbeEvidence {
	return ProbeEvidence{
		ProbeID: %s,
		Observation: %s,
		Accepted: %t,
		Contradiction: %t,
		Capability: %s,
		Effect: %s,
		Reason: %s,
		EvidenceDigest: %s,
		InputDigest: input.FixtureDigest,
		RunnerDigest: %s,
		ToolchainDigest: %s,
	}
}
`, quote(probe.CaseID+":"+probe.Operation), quote(probe.Observation), evidence.Accepted, evidence.Contradiction, quote(probe.Capability), quote(probe.Effect), quote(evidence.Reason), quote(evidence.EvidenceDigest), quote(evidence.RunnerDigest), quote(evidence.ToolchainDigest))
}

func transitionTarget(caseReport CaseReport) string {
	if len(caseReport.ClaimTransitions) == 0 {
		return LifecycleOpen
	}
	return caseReport.ClaimTransitions[0].To
}

func quote(value string) string {
	return strconv.Quote(value)
}

func WriteSummary(path string, report Report) error {
	var builder strings.Builder
	builder.WriteString("# gooo-resolution-descent-debugger conformance\n\n")
	fmt.Fprintf(&builder, "decision=%s cases=%d closed=%d unknown=%d refuted=%d\n\n", report.Decision, report.Summary.CasesTotal, report.Summary.Closed, report.Summary.Unknown, report.Summary.Refuted)
	builder.WriteString("| case | decision | before frontier | after frontier | before blocked_by | after blocked_by | transition |\n")
	builder.WriteString("| --- | --- | ---: | ---: | --- | --- | --- |\n")
	for _, caseReport := range report.Cases {
		transition := ""
		if len(caseReport.ClaimTransitions) > 0 {
			transition = caseReport.ClaimTransitions[0].From + "->" + caseReport.ClaimTransitions[0].To
		}
		fmt.Fprintf(&builder, "| %s | %s | %d | %d | %s | %s | %s |\n", caseReport.CaseID, caseReport.Decision, caseReport.BeforeUnknownFrontierCardinality, caseReport.AfterUnknownFrontierCardinality, strings.Join(caseReport.BeforeBlockedBy, ","), strings.Join(caseReport.AfterBlockedBy, ","), transition)
	}
	builder.WriteString("\nThe original OPEN claim is retained in every case; cardinality alone never closes a claim.\n")
	return WriteText(path, builder.String())
}
